# Generated by Django 4.2.7 on 2024-03-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraccount_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_admin',
            new_name='user_super',
        ),
    ]
